"""Tongue-in-cheek window titles for GIF Compare."""

import random

TITLES = [
    "Spot The Difference Championship",
    "GIF Wars Episode IV",
    "Pixels Under The Microscope",
    "The Frame Blame Game",
    "Neural Net Reality Check",
    "Who Rendered It Better",
    "Artifact Hunter Pro Edition",
    "The Blurry Truth Revealer",
    "Compression Crimes Investigation Unit",
    "Ground Truth Or Dare",
    "PSNR Anxiety Disorder Simulator",
    "Model Output Shame Parade",
    "The Uncanny Valley Inspector",
    "Temporal Consistency Torture Device",
    "Where Did My Details Go",
    "Aliasing Anonymous Support Group",
    "The Flicker Of Disappointment",
    "Blocky Nightmare Fuel Viewer",
    "Your Loss Function Lied",
    "SSIM Score Copium Dispenser",
    "Gradient Descent Gone Wrong",
    "The Overfitting Evidence Locker",
    "Motion Blur Blame Assigner",
    "Checkerboard Of Broken Dreams",
    "The Jittery Artifact Museum",
    "When Predictions Go Wrong",
    "Perceptual Loss Reality Check",
    "The Resolution Downgrade Detector",
    "Hallucination Or Feature Debate",
    "Side By Side Sadness",
    "The Temporal Wobble Tracker",
    "Ghosting Artifact Ghost Hunters",
    "Why Is It Purple",
    "The Ringing Artifact Orchestra",
    "Your Training Was Insufficient",
    "Edge Preservation Failure Analysis",
    "The Color Shift Blame Game",
    "Diffusion Model Dice Roll",
    "Latent Space Gone Latent",
    "The Reconstruction Error Museum",
    "My Model Ate My Details",
    "High Frequency Detail Graveyard",
    "The Banding Artifact Exhibit",
    "Interpolation Crimes And Misdemeanors",
    "Texture Synthesis Gone Wild",
    "The Posterization Hall Of Fame",
    "GAN Artifact Bingo Night",
    "Mode Collapse Evidence Room",
    "The Blotchy Mess Investigator",
    "Your Discriminator Was Fooled",
    "Frame Dropping Trauma Center",
    "The Temporal Aliasing Archives",
    "Bilinear Sampling Crime Scene",
    "When Upscaling Goes Wrong",
    "The Nearest Neighbor Nightmare",
    "Subpixel Accuracy Skeptics Club",
    "Denoising Disaster Documentation",
    "The Smoothing Sledgehammer Effect",
    "Frequency Domain Failure Files",
    "Your Encoder Is Crying",
    "The Bottleneck Blame Bureau",
    "Quantization Error Appreciation Society",
    "The Decoder Disappointment Diary",
    "Skip Connection Skeptics Anonymous",
    "Attention Mechanism Attention Seeker",
    "The Residual Learning Residue",
    "Batch Norm Gone Batch Wild",
    "The Dropout Disaster Logs",
    "Learning Rate Was Too High",
    "Vanishing Gradient Memorial Park",
    "The Exploding Gradient Exhibit",
    "Your Augmentation Was Weird",
    "The Preprocessing Pipeline Disaster",
    "Normalization Nightmare Navigator",
    "The Feature Map Fumble",
    "Activation Function Regret Room",
    "ReLU Dead Zone Detector",
    "The Sigmoid Saturation Station",
    "Softmax Confidence Crash Course",
    "Your Labels Were Wrong",
    "The Annotation Anger Room",
    "Dataset Bias Blame Board",
    "The Distribution Shift Shocker",
    "Out Of Domain Detector",
    "The Generalization Gap Gallery",
    "Memorization Vs Learning Court",
    "The Test Set Leak Detector",
    "Validation Loss Lie Detector",
    "Early Stopping Regret Calculator",
    "The Checkpoint Comparison Chaos",
    "Hyperparameter Hell Navigator",
    "The Architecture Ablation Attic",
    "Baseline Beating Barely Bureau",
    "State Of The Art Skeptic",
    "The Benchmark Gaming Gazette",
    "Cherry Picked Results Revealer",
    "The P Value Pretender",
    "Standard Deviation Denial Den",
    "Reproducibility Crisis Center",
    "The Random Seed Roulette",
]

def get_random_title() -> str:
    """Get a random tongue-in-cheek title."""
    return random.choice(TITLES)

def get_title_by_index(index: int) -> str:
    """Get title by index (wraps around)."""
    return TITLES[index % len(TITLES)]
